### ISSUE TITLE
Capture exception

### ISSUE THREAD

**Issue by jfear** [jfear/sramongo#12]
Need to capture this exception and say to re-run:

```
Traceback (most recent call last):
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/http/client.py", line 1260, in connect
    server_hostname=server_hostname)
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jfear/miniconda3/envs/testSra/bin/sra2mongo", line 11, in <module>
    load_entry_point('sramongo==0.0.1', 'console_scripts', 'sra2mongo')()
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/site-packages/sramongo/sra2mongo.py", line 349, in main
    fetch_sra(sra_query, cache)
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/site-packages/sramongo/sra2mongo.py", line 218, in fetch_sra
    retstart=start, **options)
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/site-packages/Bio/Entrez/__init__.py", line 180, in efetch
    return _open(cgi, variables, post=post)
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/site-packages/Bio/Entrez/__init__.py", line 527, in _open
    handle = _urlopen(cgi)
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 60] Operation timed out>
```

**Comment by jfear** [comment]
Also have

```
Traceback (most recent call last):
  File "/Users/jfear/miniconda3/envs/testSra/bin/sra2mongo", line 11, in <module>
    load_entry_point('sramongo==0.0.1', 'console_scripts', 'sra2mongo')()
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/site-packages/sramongo/sra2mongo.py", line 352, in main
    parse_sra(cache)
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/site-packages/sramongo/sra2mongo.py", line 244, in parse_sra
    for xml, runinfo in cache:
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/site-packages/sramongo/sra2mongo.py", line 70, in __iter__
    for f in sorted(self.cached):
TypeError: unorderable types: str() < int()
```

**Comment by jfear** [comment]
Also

```
Traceback (most recent call last):
  File "/Users/jfear/miniconda3/envs/testSra/bin/sra2mongo", line 11, in <module>
    load_entry_point('sramongo==0.0.1', 'console_scripts', 'sra2mongo')()
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/site-packages/sramongo/sra2mongo.py", line 352, in main
    parse_sra(cache)
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/site-packages/sramongo/sra2mongo.py", line 271, in parse_sra
    Ncbi.objects(pk=sraExperiment.srx).modify(upsert=True, sra=sraExperiment.sra)
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/site-packages/mongoengine/queryset/manager.py", line 37, in __get__
    queryset = queryset_class(owner, owner._get_collection())
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/site-packages/mongoengine/document.py", line 205, in _get_collection
    cls.ensure_indexes()
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/site-packages/mongoengine/document.py", line 851, in ensure_indexes
    **index_opts)
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/site-packages/pymongo/collection.py", line 1529, in create_index
    self.__create_index(keys, kwargs)
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/site-packages/pymongo/collection.py", line 1417, in __create_index
    with self._socket_for_writes() as sock_info:
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/site-packages/pymongo/mongo_client.py", line 823, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/site-packages/pymongo/topology.py", line 214, in select_server
    address))
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/site-packages/pymongo/topology.py", line 189, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 61] Connection refused
```

**Comment by jfear** [comment]
I think I have fixed the first two issues, won't know until I do some real world battle testing. I have moved the last issue to #13 because it is unrelated to the first two.

**Comment by jfear** [comment]
Duplicate of #13 and #28
