### ISSUE TITLE
MongoDB Connection Refused [Errno 61]

### ISSUE THREAD

**Issue by jfear** [jfear/sramongo#13]
Recently I started getting this error when trying to start and connect to a mongodb instance.

```
Traceback (most recent call last):
  File "/Users/jfear/miniconda3/envs/testSra/bin/sra2mongo", line 11, in <module>
    load_entry_point('sramongo==0.0.1', 'console_scripts', 'sra2mongo')()
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/site-packages/sramongo/sra2mongo.py", line 352, in main
    parse_sra(cache)
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/site-packages/sramongo/sra2mongo.py", line 271, in parse_sra
    Ncbi.objects(pk=sraExperiment.srx).modify(upsert=True, sra=sraExperiment.sra)
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/site-packages/mongoengine/queryset/manager.py", line 37, in __get__
    queryset = queryset_class(owner, owner._get_collection())
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/site-packages/mongoengine/document.py", line 205, in _get_collection
    cls.ensure_indexes()
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/site-packages/mongoengine/document.py", line 851, in ensure_indexes
    **index_opts)
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/site-packages/pymongo/collection.py", line 1529, in create_index
    self.__create_index(keys, kwargs)
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/site-packages/pymongo/collection.py", line 1417, in __create_index
    with self._socket_for_writes() as sock_info:
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/site-packages/pymongo/mongo_client.py", line 823, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/site-packages/pymongo/topology.py", line 214, in select_server
    address))
  File "/Users/jfear/miniconda3/envs/testSra/lib/python3.5/site-packages/pymongo/topology.py", line 189, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 61] Connection refused
```

**Comment by jfear** [comment]
I am thinking this is an issue with the host name, port, of mongo db may have crashed. Should probably just catch the error and gracefully return some suggestions for fixing.
