### ISSUE TITLE
another error

### ISSUE THREAD

**Issue by jfear** [jfear/sramongo#18]
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1260, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sramongo/sra2mongo.py", line 241, in fetch_ncbi
    xml_handle = Entrez.efetch(retmode='xml', retstart=start, **options)
  File "/usr/local/lib/python3.5/dist-packages/Bio/Entrez/__init__.py", line 180, in efetch
    return _open(cgi, variables, post=post)
  File "/usr/local/lib/python3.5/dist-packages/Bio/Entrez/__init__.py", line 527, in _open
    handle = _urlopen(cgi)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:645)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/sra2mongo", line 11, in <module>
    load_entry_point('sramongo==0.0.1', 'console_scripts', 'sra2mongo')()
  File "/usr/local/lib/python3.5/dist-packages/sramongo/sra2mongo.py", line 447, in main
    raise err
  File "/usr/local/lib/python3.5/dist-packages/sramongo/sra2mongo.py", line 394, in main
    fetch_ncbi(sra_query, cache)
  File "/usr/local/lib/python3.5/dist-packages/sramongo/sra2mongo.py", line 274, in fetch_ncbi
    if (err.code == 60) & (attempt < 3):
AttributeError: 'URLError' object has no attribute 'code'
ubuntu@ubuntu-xenial:~$
```

**Comment by jfear** [comment]
2017-07-17 14:55:47,970 - INFO - Parsing SRA XML
Traceback (most recent call last):
  File "/opt/conda/bin/sra2mongo", line 11, in <module>
    load_entry_point('sramongo==0.0.2', 'console_scripts', 'sra2mongo')()
  File "/opt/conda/lib/python3.5/site-packages/sramongo-0.0.2-py3.5.egg/sramongo/sra2mongo.py", line 447, in main
  File "/opt/conda/lib/python3.5/site-packages/sramongo-0.0.2-py3.5.egg/sramongo/sra2mongo.py", line 397, in main
  File "/opt/conda/lib/python3.5/site-packages/sramongo-0.0.2-py3.5.egg/sramongo/sra2mongo.py", line 314, in parse_sra
  File "/opt/conda/lib/python3.5/site-packages/mongoengine-0.11.0-py3.5.egg/mongoengine/queryset/manager.py", line 37, in __get__
  File "/opt/conda/lib/python3.5/site-packages/mongoengine-0.11.0-py3.5.egg/mongoengine/document.py", line 205, in _get_collection
  File "/opt/conda/lib/python3.5/site-packages/mongoengine-0.11.0-py3.5.egg/mongoengine/document.py", line 820, in ensure_indexes
  File "/opt/conda/lib/python3.5/site-packages/pymongo/collection.py", line 1387, in create_index
    self.__create_index(keys, kwargs)
  File "/opt/conda/lib/python3.5/site-packages/pymongo/collection.py", line 1294, in __create_index
    with self._socket_for_writes() as sock_info:
  File "/opt/conda/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/opt/conda/lib/python3.5/site-packages/pymongo/mongo_client.py", line 762, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/opt/conda/lib/python3.5/site-packages/pymongo/topology.py", line 210, in select_server
    address))
  File "/opt/conda/lib/python3.5/site-packages/pymongo/topology.py", line 186, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused

**Comment by jfear** [comment]
```bash
k2017-07-17 16:09:36,997 - INFO - Querying BioSample: with 26,587 ids
2017-07-17 16:09:36,997 - INFO - Saving to cache: /data/.cache/sra2mongo/biosample
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/opt/conda/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/opt/conda/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/opt/conda/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/opt/conda/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/opt/conda/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/opt/conda/lib/python3.5/http/client.py", line 1261, in connect
    server_hostname=server_hostname)
  File "/opt/conda/lib/python3.5/ssl.py", line 385, in wrap_socket
    _context=self)
  File "/opt/conda/lib/python3.5/ssl.py", line 760, in __init__
    self.do_handshake()
  File "/opt/conda/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/opt/conda/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/sra2mongo", line 11, in <module>
    load_entry_point('sramongo==0.0.2', 'console_scripts', 'sra2mongo')()
  File "/opt/conda/lib/python3.5/site-packages/sramongo-0.0.2-py3.5.egg/sramongo/sra2mongo.py", line 447, in main
  File "/opt/conda/lib/python3.5/site-packages/sramongo-0.0.2-py3.5.egg/sramongo/sra2mongo.py", line 405, in main
  File "/opt/conda/lib/python3.5/site-packages/sramongo-0.0.2-py3.5.egg/sramongo/sra2mongo.py", line 187, in ncbi_query
  File "/opt/conda/lib/python3.5/site-packages/Bio/Entrez/__init__.py", line 216, in esearch
    return _open(cgi, variables)
  File "/opt/conda/lib/python3.5/site-packages/Bio/Entrez/__init__.py", line 525, in _open
    handle = _urlopen(cgi, data=_as_bytes(options))
  File "/opt/conda/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/conda/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/opt/conda/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/opt/conda/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/opt/conda/lib/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/opt/conda/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>
[root@centos-7 simple_docker]#
```

**Comment by jfear** [comment]
Split these up into #25, #26, and #27.

Just trying to organize.
