### ISSUE TITLE
MongoDB Server Timeout [Errno 111]

### ISSUE THREAD

**Issue by jfear** [jfear/sramongo#26]
I can't remember the exact command I used to run this. I am guessing the issue was providing the wrong port number of mongoDB. Still would be good to capture this cleanly and give some suggestions for fixing.

```bash
2017-07-17 14:55:47,970 - INFO - Parsing SRA XML
Traceback (most recent call last):
  File "/opt/conda/bin/sra2mongo", line 11, in <module>
    load_entry_point('sramongo==0.0.2', 'console_scripts', 'sra2mongo')()
  File "/opt/conda/lib/python3.5/site-packages/sramongo-0.0.2-py3.5.egg/sramongo/sra2mongo.py", line 447, in main
  File "/opt/conda/lib/python3.5/site-packages/sramongo-0.0.2-py3.5.egg/sramongo/sra2mongo.py", line 397, in main
  File "/opt/conda/lib/python3.5/site-packages/sramongo-0.0.2-py3.5.egg/sramongo/sra2mongo.py", line 314, in parse_sra
  File "/opt/conda/lib/python3.5/site-packages/mongoengine-0.11.0-py3.5.egg/mongoengine/queryset/manager.py", line 37, in __get__
  File "/opt/conda/lib/python3.5/site-packages/mongoengine-0.11.0-py3.5.egg/mongoengine/document.py", line 205, in _get_collection
  File "/opt/conda/lib/python3.5/site-packages/mongoengine-0.11.0-py3.5.egg/mongoengine/document.py", line 820, in ensure_indexes
  File "/opt/conda/lib/python3.5/site-packages/pymongo/collection.py", line 1387, in create_index
    self.__create_index(keys, kwargs)
  File "/opt/conda/lib/python3.5/site-packages/pymongo/collection.py", line 1294, in __create_index
    with self._socket_for_writes() as sock_info:
  File "/opt/conda/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/opt/conda/lib/python3.5/site-packages/pymongo/mongo_client.py", line 762, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/opt/conda/lib/python3.5/site-packages/pymongo/topology.py", line 210, in select_server
    address))
  File "/opt/conda/lib/python3.5/site-packages/pymongo/topology.py", line 186, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
```

**Comment by jfear** [comment]
Similar error seen in #13, but different error number.
