### ISSUE TITLE
Providing email and API causes retmax error

### ISSUE THREAD

**Issue by jfear** [jfear/sramongo#31]
```
Traceback (most recent call last):
  File "/home/fearjm/miniconda3/envs/sramongo/bin/sra2mongo", line 11, in <module>
    load_entry_point('sramongo==1.1.1', 'console_scripts', 'sra2mongo')()
  File "/home/fearjm/miniconda3/envs/sramongo/lib/python3.7/site-packages/sramongo-1.1.1-py3.7.egg/sramongo/sra2mongo.py", line 392, in main
  File "/home/fearjm/miniconda3/envs/sramongo/lib/python3.7/site-packages/sramongo-1.1.1-py3.7.egg/sramongo/sra2mongo.py", line 71, in run_sra2mongo
  File "/home/fearjm/miniconda3/envs/sramongo/lib/python3.7/site-packages/sramongo-1.1.1-py3.7.egg/sramongo/sra2mongo.py", line 93, in check_sra_for_updated_ids
  File "/home/fearjm/miniconda3/envs/sramongo/lib/python3.7/site-packages/sramongo-1.1.1-py3.7.egg/sramongo/services/entrez.py", line 68, in esearch
  File "/home/fearjm/miniconda3/envs/sramongo/lib/python3.7/site-packages/sramongo-1.1.1-py3.7.egg/sramongo/services/entrez.py", line 324, in check_email
NameError: name 'retmax' is not defined
```

**Comment by jfear** [comment]
This appears to be a copy-paste error that is fixed in #32.
